### ISSUE TITLE
implicit declaration would take non-const

### ISSUE THREAD

**Issue by bgoodri** [SteveBronder/pathfinder_testing#1]
I can build the develop branch of cmdstan with the stan repo at c492f71eb, but I can't get the feature/multi-branch to build with cmdstan. I get

> In file included from /usr/include/c++/8/functional:54,
                 from stan/lib/stan_math/lib/eigen_3.3.9/Eigen/Core:281,
                 from stan/lib/stan_math/lib/eigen_3.3.9/Eigen/Dense:1,
                 from stan/lib/stan_math/stan/math/prim/fun/Eigen.hpp:22,
                 from stan/src/stan/callbacks/writer.hpp:4,
                 from src/cmdstan/arguments/argument.hpp:4,
                 from src/cmdstan/arguments/categorical_argument.hpp:4,
                 from src/cmdstan/arguments/arg_data.hpp:4,
                 from src/cmdstan/command.hpp:4,
                 from src/cmdstan/main.cpp:1:
/usr/include/c++/8/tuple: In instantiation of ‘struct std::_Head_base<3, stan::callbacks::unique_stream_writer<std::basic_ostream<char> >, false>’:
/usr/include/c++/8/tuple:185:12:   recursively required from ‘struct std::_Tuple_impl<1, std::vector<stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > >, std::allocator<stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > > > >, stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > >, stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > > >’
/usr/include/c++/8/tuple:185:12:   required from ‘struct std::_Tuple_impl<0, std::vector<stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > >, std::allocator<stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > > > >, std::vector<stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > >, std::allocator<stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > > > >, stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > >, stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > > >’
/usr/include/c++/8/tuple:556:11:   required from ‘class std::tuple<std::vector<stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > >, std::allocator<stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > > > >, std::vector<stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > >, std::allocator<stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > > > >, stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > >, stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > > >’
src/cmdstan/command.hpp:405:25:   required from ‘auto cmdstan::setup_writers(Model&&, Parser&&, unsigned int, std::vector<std::__cxx11::basic_string<char> >&) [with Model = stan::model::model_base&; Parser = cmdstan::argument_parser&]’
src/cmdstan/command.hpp:571:82:   required from here
/usr/include/c++/8/tuple:128:17: error: ‘constexpr std::_Head_base<_Idx, _Head, false>::_Head_base(const std::_Head_base<_Idx, _Head, false>&) [with long unsigned int _Idx = 3; _Head = stan::callbacks::unique_stream_writer<std::basic_ostream<char> >]’ declared to take const reference, but implicit declaration would take non-const
       constexpr _Head_base(const _Head_base&) = default;
                 ^~~~~~~~~~
/usr/include/c++/8/tuple: In instantiation of ‘struct std::_Head_base<2, stan::callbacks::unique_stream_writer<std::basic_ostream<char> >, false>’:
/usr/include/c++/8/tuple:185:12:   recursively required from ‘struct std::_Tuple_impl<1, std::vector<stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > >, std::allocator<stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > > > >, stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > >, stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > > >’
/usr/include/c++/8/tuple:185:12:   required from ‘struct std::_Tuple_impl<0, std::vector<stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > >, std::allocator<stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > > > >, std::vector<stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > >, std::allocator<stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > > > >, stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > >, stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > > >’
/usr/include/c++/8/tuple:556:11:   required from ‘class std::tuple<std::vector<stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > >, std::allocator<stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > > > >, std::vector<stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > >, std::allocator<stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > > > >, stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > >, stan::callbacks::unique_stream_writer<std::basic_ostream<char, std::char_traits<char> > > >’
src/cmdstan/command.hpp:405:25:   required from ‘auto cmdstan::setup_writers(Model&&, Parser&&, unsigned int, std::vector<std::__cxx11::basic_string<char> >&) [with Model = stan::model::model_base&; Parser = cmdstan::argument_parser&]’
src/cmdstan/command.hpp:571:82:   required from here
/usr/include/c++/8/tuple:128:17: error: ‘constexpr std::_Head_base<_Idx, _Head, false>::_Head_base(const std::_Head_base<_Idx, _Head, false>&) [with long unsigned int _Idx = 2; _Head = stan::callbacks::unique_stream_writer<std::basic_ostream<char> >]’ declared to take const reference, but implicit declaration would take non-const

**Comment by SteveBronder** [comment]
Sorry I think while I was trying to fix something on Friday I made a goof, I will fix this this on Monday!

**Comment by SteveBronder** [comment]
I was able to replicate this locally and pushed up a version of cmdstan with a fix, lmk if it works for you!

**Comment by bgoodri** [comment]
Fixed by 11ebe6ec3a56a6fb67d87e7f9f1c7ca21aff81b7 Thanks!
